 	      	ORG 0000H   ;STARTING ADDRESS
 		LJMP LABEL1
	  	ORG 000BH ;ADDRESS OF ISR ROUTINE
 		AJMP ISR_ROUTINE
       
LABEL1: CLR P1.2 ;CLR THE PORT PIN FROM ANY PREVIOUS VALUE
 		MOV TMOD, #01H  ;SELECTING TIMER 0 IN MODE 1  
		MOV R1,#08H  ;USING R1 AS A COUNTER TO RUN THE TIMER REGISTER 8 TIMES
		
		MOV TH0, #0F7H ;LOADING THE VALUES INTO TIMER REGISTER
						;TLO AND THO DEPENDING ON THE DELAY OF LED 
 		MOV TL0, #0F8H			
		SETB TR0 ;TRO SET TO START THE TIMER 0 COUNT
 		MOV IE,#082H ; ENABLING INTERRUPT ENABLE REGISTER FOR TIMER TIMER 0 OVERLFLOW
 	
LOOP:	AJMP LOOP; KEEP REPEATING THE LOOP TILL INTERRUPT COMES
;: AJMP LABEL1	
 				
      			
ISR_ROUTINE:SETB P1.0 ;SET ANOTHER PORT PIN TO CHECK THE TIME PROGRAM IS IN ISR
			DJNZ R1,REPEAT ;DECREMENT R1 AND JUMP TO RUN TIMER ONCE AGAIN IF DESIRED DELAY NOT OBTAINED
 			CPL P1.2; COMPLEMENT THE LED PORT ONCE REQUIRED DELAY IS ACHIEVED
			MOV R1,#08H ; RELOAD VALUE OF R1 TO 8 TO RESTART 
			MOV TH0, #0F7H ; RELOAD VALUE OF THO TO RESTART
 			MOV TL0, #0F8H	;  RELOAD VALUE OF TLO TO RESTART
		
      			
REPEAT:		CLR P1.0 ;CLEAR 2ND PORT PIN TO CALCULATE TIME PROGRAM IS IN ISR 
			RETI ;RETURN TO PROGRAM FROM THE ISR
